// This file will be auto-generated by running: npm run db:generate
// For now, we'll define the basic structure

export interface Database {
  public: {
    Tables: {
      diagnoses: {
        Row: {
          id: string;
          name: string;
          synonyms: string[] | null;
          specialty: string;
          icd10: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          synonyms?: string[] | null;
          specialty: string;
          icd10?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          synonyms?: string[] | null;
          specialty?: string;
          icd10?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      history_templates: {
        Row: {
          id: string;
          diagnosis_id: string | null;
          diagnosis_name: string;
          specialty: string;
          sections: any; // JSON type
          generated_by: 'llm' | 'manual';
          llm_model: string | null;
          created_at: string;
          updated_at: string;
          cached: boolean;
          access_count: number;
          last_accessed: string | null;
        };
        Insert: {
          id?: string;
          diagnosis_id?: string | null;
          diagnosis_name: string;
          specialty: string;
          sections: any;
          generated_by: 'llm' | 'manual';
          llm_model?: string | null;
          created_at?: string;
          updated_at?: string;
          cached?: boolean;
          access_count?: number;
          last_accessed?: string | null;
        };
        Update: {
          id?: string;
          diagnosis_id?: string | null;
          diagnosis_name?: string;
          specialty?: string;
          sections?: any;
          generated_by?: 'llm' | 'manual';
          llm_model?: string | null;
          created_at?: string;
          updated_at?: string;
          cached?: boolean;
          access_count?: number;
          last_accessed?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      increment_template_access: {
        Args: {
          template_id: string;
        };
        Returns: void;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
} 